WatchMe/WatchMe/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WatchMe.DAL;
using Microsoft.AspNet.Identity;

namespace WatchMe.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManageUsersController : Controller
    {
        private BinoclrDBEntities db = new BinoclrDBEntities();

        // GET: ManageUsers
        public async Task<ActionResult> Index()
        {
            return View(await db.Users.ToListAsync());
        }

        // GET: ManageUsers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: ManageUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManageUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Private,Email,Status,ProfilePic,Security_Question,Security_Answer,SignUpDate,LastLogin,Admin,AccessFailedCount,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,UserName,DateOfBirth")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: ManageUsers/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: ManageUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Private,Email,Status,ProfilePic,Security_Question,Security_Answer,SignUpDate,LastLogin,Admin,AccessFailedCount,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,UserName,DateOfBirth")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: ManageUsers/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: ManageUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            User user = await db.Users.FindAsync(id);

            db.Followers.RemoveRange(db.Followers.Where(f => f.UserId == id || f.FollowerId == id));
            db.SaveChanges();

            db.Followings.RemoveRange(db.Followings.Where(f => f.UserId == id || f.FollowingId == id));
            db.SaveChanges();

            db.Users.Remove(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

WatchMe/WatchMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>

    <div class="navbar">
        <div id="banner">
            <img id="img_logo" alt="Logo" src="@Url.Content("~/Content/Images/BinoclrBanner.png")" />
        </div>
        <div id="nav_bar">
        <div class="container navbar-inverse" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Binoclr", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated || User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Broadcast", "Broadcast", "Broadcast")</li>
                        <li>@Html.ActionLink("Search", "Index", "Search")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Manage", "Index", "ManageUsers")</li>
                        <li>@Html.ActionLink("Roles", "Index", "Roles")</li>
                    }
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
                
            </div>
        </div>
          </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        
        <hr />
        <div>
        @Html.Partial("_NotificationPartial")
        </div>













        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>

        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/navbar")
    @RenderSection("scripts", required: false)
</body>
</html>

WatchMe/WatchMe/Views/Shared/_NotificationPartial.cshtml
@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right" id="BottomNav" >
        
        @Html.Partial("_OnlineFollowingPartial")

        <li class="dropup" >

                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    @*Notification*@ 
                    @*<span class="caret"></span>*@
                    <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>

                </button>
                <ul class="dropdown-menu" id="notificationTab">
                    <li><a href="#" id="noNoti">No Notification</a></li>                
                </ul>
            
        </li>


</ul>

}
else
{

}

<script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
<script src="~/signalr/hubs"></script>
<script>

   $(function() {
      // Save the reference to the SignalR hub
      var notification = $.connection.notificationHub;

      // Invoke the function to be called back from the server
      // when changes are detected
      notification.client.addNewNotificationToPage = function (notification, id) {
          // Add the message to the page.
          
          console.log(notification);
          $('#notificationTab').prepend('<li><a>' + notification
              + '</a></li>');

          //onClickHandler lead to profile of id
      };

      notification.client.LoadNotificationsToPage = function (notifications)
      {
          for (i = 0; i < notifications.length; i++)
          {
              $('#notificationTab').prepend('<li><strong>' + notifications[i]
              + '</strong> </li>');
          }
      }

      // Start the SignalR client-side listener
      $.connection.hub.start().done(function () {
          // Do here any initialization work you may need
          console.log("Connected");
          var id = "@User.Identity.GetUserId()";
          console.log("Id: " + id);

          notification.server.fetchNotification(id);
         
      });

      $.connection.hub.start().fail(function (error) {
          // Do here any initialization work you may need
          console.log("Connection fail"+ error);

      });

      $.connection.hub.disconnected(function () {
          setTimeout(function () {
              $.connection.hub.start();
          }, 5000); // Re-start connection after 5 seconds
      });
   });
</script>

WatchMe/WatchMe/Views/Shared/_OnlineFollowingPartial.cshtml
@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    <div id="watchBroadcastBackground">
    </div>
        <div id="watchBroadcast">
            <img id="closeButton" src="~/Content/Images/close_icon.png" />"/>
            <video id="RemoteVideo" autoplay></video>
        </div>
    
        <li class="dropup">

            <button id="onlinebtn" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                Online
                @*<span class="glyphicon glyphicon-bell" aria-hidden="true"></span>*@
            </button>
            <ul class="dropdown-menu" id="onlineTab">
                <li><a href="#" id="noOnline">No Online</a></li>
            </ul>

        </li>

        }
        else
        {

        }

        <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
        <script src="~/signalr/hubs"></script>
        <script>
            $(function () {
                document.getElementById('watchBroadcastBackground').style.visibility = "hidden";
                document.getElementById('watchBroadcast').style.visibility = "hidden";

                var broadcastHub = $.connection.broadcastHub;
                var iceServers = [{ url: 'stun:74.125.142.127:19302' }];
                var RTCPeerConnection = window.RTCPeerConnection || window.mozRTCPeerConnection || window.webkitRTCPeerConnection;
                var connection = new RTCPeerConnection({ iceServers: iceServers });;
                var id = "@User.Identity.GetUserId()";
                var broadcaster = false;;
                var isConnected = false;;
                var accepted = false;
                function error(e) {
                    console.log("Error: " + e);
                }

                function getMedia() {
                    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
                    navigator.getUserMedia({ video: true, audio: true }, function (stream) {
                        //Add stream and set up local video
                        connection.addStream(stream);

                        setLocalVideo(stream);
                        initiate();
                    }, error);
                }

                function setLocalVideo(stream) {
                    //var localVideo = $("#localVideo");
                    //var video = document.querySelector('video');
                    var video = document.getElementById('localVideo');
                    video.src = window.URL.createObjectURL(stream);

                }

                function sendOffer(offer) {
                    //broadcastHub.server.send(JSON.stringify(offer));
                    console.log("Sending offer to hub");
                    broadcastHub.server.sendBroadcastToFollower(id, JSON.stringify(offer));
                }

                function sendAccept(broadcasterId, accept) {
                    //broadcastHub.server.send(JSON.stringify(offer));
                    //var id = "@User.Identity.GetUserId()";
                    console.log("send Accept");
                    broadcastHub.server.sendAcceptToBroadcaster(broadcasterId, id, JSON.stringify(accept));
                    isConnected = true;
                }

                function initiate() {
                    //Create and send offer
                    connection.createOffer(function (offer) {
                        console.log(offer);
                        connection.setLocalDescription(new RTCSessionDescription(offer), sendOffer(offer), error);
                    }, error);
                }

                function answer(broadcasterId, offer) {

                    connection.setRemoteDescription(new RTCSessionDescription(offer), function () {
                        connection.createAnswer(function (answer) {
                            connection.setLocalDescription(new RTCSessionDescription(answer), function () {
                                sendAccept(broadcasterId, answer)
                            }, error);
                        }, error);
                    },error);
                }


                var broadcasterId;

                broadcastHub.client.receive = function (receivedId, message, context) {
                    var obj = JSON.parse(context);
                    if (obj.sdp && obj.type === "offer") {
                        console.log(receivedId + " is broadcasting");
                        $('#onlineTab').prepend('<li>' + '<a target="_blank" id=' + receivedId + ' class="broadcastLink">' + message + '</a>' + '</li>');
                        var none = document.getElementById("noOnline");
                        none.style.visibility = "hidden";
                        broadcasterId = receivedId;
                        //$('#onlineTab').prepend('<li >' + '<a data-id=' + receivedId + ' class="broadcastLink" href="@Url.Action("WatchBroadcast","Broadcast")?connection=' + context + '">' + receivedId + '</a>' + '</li>');
                        var link = document.getElementById(receivedId);
                        link.onclick = function () {
                            document.getElementById('watchBroadcastBackground').style.visibility = "visible";
                            document.getElementById('watchBroadcast').style.visibility = "visible";

                            console.log("answer");
                            answer(receivedId, obj);


                        }
                    }
                    else if (obj.sdp && obj.type === "answer") {
                        console.log("Answer: " + context);
                        accepted = true;
                        connection.setRemoteDescription(new RTCSessionDescription(obj), function () { }, error);
                    }
                    else if (obj.candidate) {
                        console.log("reply: " + obj);
                        connection.addIceCandidate(new RTCIceCandidate(obj));
                    }
                }

                connection.onicecandidate = function (e) {
                    if (e.candidate == null) { return }
                    //broadcastHub.server.send(JSON.stringify(e));
                    if (broadcaster && accepted) {
                        console.log("send ice to follower")
                        broadcastHub.server.sendIceToFollower(id, JSON.stringify(e.candidate));
                    }
                    else {
                        if (isConnected)
                            console.log("send ice to broadcaster")
                            broadcastHub.server.sendIceToBroadcaster(broadcasterId, JSON.stringify(e.candidate));
                    }
                }



                $.connection.hub.start().done(function () {
                    startConnection();
                });

                function startConnection() {
                    $.connection.hub.start().done(function () {
                        console.log("Connected Broadcast");
                        var id = "@User.Identity.GetUserId()";
                        //broadcastHub.server.getLiveBroadcast(id)
                        $("#startButton").attr("disabled", false);
                    });
                }

                $("#startButton").click(function () {
                    console.log("Start clicked");
                    getMedia();
                    broadcaster = true;
                    $("#startButton").attr("disabled", true);
                    $("#endButton").attr("disabled", false);

                })

                $("#endButton").click(function () {

                    $("#endButton").attr("disabled", true);
                    var video = document.getElementById("localVideo");
                    video.src = null;
                    video.pause();
                    $.connection.hub.stop();
                });

                $.connection.hub.start().fail(function (error) {
                    // Do here any initialization work you may need
                    console.log("Connection fail" + error);

                });

                $.connection.hub.disconnected(function () {
                    $("#startButton").attr("disabled", true);
                    setTimeout(function () {
                        startConnection();
                    }, 5000); // Re-start connection after 5 seconds


                });

                connection.onaddstream = function (obj) {
                    //console.log("Ice connection State"+ obj.srcElement.iceConnectionState);
                    //console.log("Ice cGathering State" + obj.srcElement.iceGatheringState);
                    //if (obj.srcElement.iceConnectionState === 'connected' && obj.srcElement.iceGatheringState === 'complete') {
                    //    console.log("ice Gather Complete ");

                    var vid = document.getElementById("RemoteVideo");
                    vid.src = window.URL.createObjectURL(obj.stream);
                    console.log(obj.stream);
                    vid.load();
                    vid.play();
                    //}

                }




            });

        </script>